### PR TITLE
Add Busybox auto-installer script

### PR DESCRIPTION
**Pull request by xerta555**
Hello,

As your module require the Busybox module by osm0sis to works propeply, there is an auto-installer of the Busybox module that i have ported.

All symlinks will be installed by Magisk in `/system/sbin/` folder.

Pre-request:
- Magisk v18

Tell me if you want more infos/edit(s).

Have a good day :)

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
A few things:
**First of all:** it would have been nice if you had cleaned up the Energized Protection parts before submitting. Really makes you feel special... :laughing: 
**Second:** From a quick look there are a few things in there that I don't quite understand. For example, what is the busybox_install file for and why do you chmod it (and the busybox_check script) 777?
**Lastly:** I used to have an automatic download of Busybox, based on the users architecture and all, but decided I'd rather make the user install the Busybox of their choice (with a recommendation for @osm0sis Busybox, of course). There are several reasons why I went that route, but that's for another time.

I'll reject this for now, but I'll keep it in mind in case I change my mind.

**Comment by xerta555** [comment]
> First of all: it would have been nice if you had cleaned up the Energized Protection parts before submitting. Really makes you feel special...

A little mistake on my part, a modification on my fork would have been enough.

> From a quick look there are a few things in there that I don't quite understand. For example, what is the busybox_install file for and why do you chmod it (and the busybox_check script) 777?

I assign more permissions on the file to avoid any problem, we are never too careful! 
This is the osm0sis installation script that I modified a little bit for a Magisk installation only.

> Lastly: I used to have an automatic download of Busybox, based on the users architecture and all, but decided I'd rather make the user install the Busybox of their choice (with a recommendation for @osm0sis Busybox, of course). There are several reasons why I went that route, but that's for another time.

For me it's just an unnecessary complication, but everyone has their own way of seeing things. At the limit I will have added the functionality of choosing by the physical volume keys of the device, for example if the user decides to refuse, then he must press the low volume key, if he accepts the automated installation, then he just has to press the other volume key.

But concerning this last idea, I don't know if this'MOD' is up to date and functional on any device with an Android ROM.

**Comment by Didgeridoohan** [comment]
That was just me trying to be funny... I've been told my sense of humour is sometimes a bit lacking. :)

I'm still curious what the busybox_install file is for, because as far as I can see that's not from @osm0sis Busybox module.

**Comment by xerta555** [comment]
> That was just me trying to be funny... I've been told my sense of humour is sometimes a bit lacking. :)

np.

> I'm still curious what the busybox_install file is for, because as far as I can see that's not from @osm0sis Busybox module.

The base script is the upgrade-binary file from his module: https://github.com/Magisk-Modules-Repo/busybox-ndk/blob/master/META-INF/com/google/android/update-binary

I have adapt it for a classic install through a terminal..

**Comment by xerta555** [comment]
> I know, I've looked at your script. But again, there's no such file (busybox_install) in the original... I get it if you would use that file as a marker for if Busybox is installed, but you're not actually using it anywhere and there would be no need for permission 777.

I have rename upgrade-binary file to busybox_check.sh and put it in the $MODPATH folder.

I was leaving you free to say where you would have liked to place the command that would have executed the automated script, which is why I didn't change your config.sh file more than that.

**Comment by Didgeridoohan** [comment]
I guess you don't understand what I'm talking about (is it really you that have modified the script?)...

Lines 11-12 and 142-143 creates a file named `busybox_install`. Line 11 in the main module folder (in this case `energizedprotection`) and on line 142 it's created in the Busybox module directory. That's what I'm wondering about.

**Comment by xerta555** [comment]
> I guess you don't understand what I'm talking about (is it really you that have modified the script?)...

Yeah I just didn't understand (or rather not read well) your question.

> Lines 11-12 and 142-143 creates a file named busybox_install

I made this part just to be able to check the proper install of the module.

**Pull request closed without merging**
