### PR TITLE
Added fingerprints for Elephone P9000/P9000E.

### PR DESCRIPTION
**Pull request by AreYouLoco**
Fingerprints added from builds got from official ROMs from the Elephone website:
https://www.elephone.hk/downloads

Should pass SafetyNet.

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
Prints did not pass the CTS profile check when tested.

**Comment by AreYouLoco** [comment]
Thats weird. Because they are taken from official image and I did pass safety with them.?

**Comment by AreYouLoco** [comment]
Thats weird. How did you test it?

**Comment by Didgeridoohan** [comment]
Tested with the module, of course, on different devices and none passed. That's just the way it is sometimes and I'm not going to pretend to understand it. Some prints doesn't pass on all devices...

I'm not saying that I don't believe that you can pass with them, it's just that I won't put a print on the list if I can't personally verify that it's working.

**Comment by AreYouLoco** [comment]
Ok fair enough.

**Pull request closed without merging**
