### PR TITLE
Update prints.sh

### PR DESCRIPTION
**Pull request by michaelmaverick**
Update Mix 2S fingerprint to 9.0.0

### CODE REVIEW

**Comment by Didgeridoohan** [comment]
The fingerprint is probably valid, but without the matching security patch date it's actually useless... Could you provide that please?

**Comment by michaelmaverick** [comment]
Sure thing. Just wondering how can I get the security patch date w/o flashing the ROM. (I got the fingerprints from the build.prop)

**Comment by Didgeridoohan** [comment]
The prop you need is `ro.build.version.security_patch`. It should be in the build.prop...

**Comment by michaelmaverick** [comment]
ro.build.version.security_patch=2018-10-01

**Comment by Didgeridoohan** [comment]
The fingerprint has been included in the latest update. Thank you very much for your contribution.

**Pull request closed without merging**
